# Generated by Django 3.2 on 2022-06-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='phone number')),
                ('email', models.CharField(blank=True, max_length=11, null=True, verbose_name='email')),
                ('code', models.CharField(max_length=4, verbose_name='code')),
                ('expire_time', models.DateTimeField(verbose_name='expire time')),
            ],
            options={
                'verbose_name': 'Otp code',
                'verbose_name_plural': 'Otp codes',
            },
        ),
    ]
